language: objective-c
osx_image: xcode8.1
rvm:
  - 2.2.3

env:
  CODE_SIGNING_REQUIRED: NO

notifications:
  email: false

xcode_project: Retired.xcodeproj
xcode_scheme: Retired iOS
xcode_sdk: iphonesimulator10.1

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

before_script:
  - carthage bootstrap --platform iOS

script:
  - xcodebuild clean build-for-testing -project Retired.xcodeproj -scheme Retired\ iOS -sdk iphonesimulator10.1
  - xcodebuild test-without-building -project Retired.xcodeproj -scheme Retired\ iOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1'
