language: objective-c
osx_image: xcode7.3
rvm:
  - 2.2.3

env:
  CODE_SIGNING_REQUIRED: NO

notifications:
  email: false

xcode_project: Retired.xcodeproj
xcode_scheme: Retired iOS
xcode_sdk: iphonesimulator9.3

before_install:
  - brew update
  - brew install carthage

before_script:
  - carthage bootstrap --platform iOS
